version: '3.3'
services:
  ialobby_server:
    build:
      context: server
    container_name: ialobby_server
    env_file: server/.env
    restart: always
    #ports:
    #  - 5000:5000

  ialobby_client:
    build:
      context: client
    container_name: ialobby_client
    env_file: client/.env
    restart: always
    depends_on:
      - ialobby_server
    #ports:
    #  - 8085:8085

  nginx_reverse_proxy:
    image: nginx
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificate.crt:/etc/nginx/certs/certificate.crt:ro
      - ./private.key:/etc/nginx/certs/private.key:ro
    depends_on:
      - ialobby_client
    ports:
      - "1443:1443" # 1443 => 8085
      - "9443:9443" # 9443 => 5000
    restart: always
